// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations precisam de conexão DIRETA (session mode). Em produção use
  // DIRECT_URL (Supabase: conexão direta, porta 5432). Runtime continua na
  // Transaction pooler (6543) via DATABASE_URL no adapter (src/lib/prisma.ts).
  // Local: DIRECT_URL não existe, cai no DATABASE_URL normalmente.
  datasource: {
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
